In [41]:
import os
os.listdir()

['.ipynb_checkpoints',
 'blinkit data.xlsx',
 'blinkit.ipynb',
 'Book1.xlsx',
 'Book2.xlsx',
 'Clean_Blinkit_Data.xlsx',
 'DIWALI_SALES.xlsx',
 'Presonal expenses.xlsx',
 'Untitled.ipynb']

In [42]:
import pandas as pd

In [43]:
df = pd.read_excel('blinkit data.xlsx')

In [44]:
df.head()

,Item Fat Content,Item Identifier,Item Type,Outlet Establishment Year,Outlet Identifier,Outlet Location Type,Outlet Size,Outlet Type,Item Visibility,Item Weight,Sales,Rating
0,Low Fast,ABC1023,Rice,2015,OUT7431,Tire1,Small,Supermarket3,83.829788,4.3,71.72,3
1,Low Fast,XYZ4587,Bread,2018,OUT1668,Tire1,Medium,Supermarket1,27.765161,2.9,41.49,3
2,Low Fast,MNP6734,Milk,2021,OUT1116,Tire2,High,Supermarket3,22.820889,5.0,86.89,3
3,Low Fast,QWE8912,Egg,2016,OUT8434,Tire1,High,Supermarket3,84.759643,1.8,73.61,4
4,Low Fast,RTY3456,Apple,2023,OUT7215,Tire1,Small,Supermarket3,90.073415,1.1,37.81,5

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110 entries, 0 to 109
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Item Fat Content           110 non-null    object
 1   Item Identifier            110 non-null    object
 2   Item Type                  110 non-null    object
 3   Outlet Establishment Year  110 non-null    int64
 4   Outlet Identifier          110 non-null    object
 5   Outlet Location Type       110 non-null    object
 6   Outlet Size                110 non-null    object
 7   Outlet Type                110 non-null    object
 8   Item Visibility            110 non-null    float64
 9   Item Weight                110 non-null    float64
 10  Sales                      110 non-null    float64
 11  Rating                     110 non-null    int64
dtypes: float64(3), int64(2), object(7)
memory usage: 10.4+ KB

In [46]:
df.tail()

,Item Fat Content,Item Identifier,Item Type,Outlet Establishment Year,Outlet Identifier,Outlet Location Type,Outlet Size,Outlet Type,Item Visibility,Item Weight,Sales,Rating
105,Regular,QRS1729,Banana,2019,OUT2042,Tire1,Small,Supermarket2,25.647501,1.8,49.19,5
106,Regular,TUV6854,Orange,2025,OUT3336,Tire3,Small,Supermarket3,52.995715,4.5,76.40,3
107,Regular,WXY3908,Mango,2017,OUT5577,Tire2,Small,Supermarket2,25.909120,4.9,60.17,5
108,Regular,ZAB7142,Grapes,2020,OUT2513,Tire1,High,Supermarket1,93.293014,1.6,93.07,5
109,Regular,CDE2587,Potato,2022,OUT5031,Tire1,Medium,Supermarket2,96.988694,2.9,46.97,5

In [47]:
df.shape

(110, 12)

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110 entries, 0 to 109
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Item Fat Content           110 non-null    object
 1   Item Identifier            110 non-null    object
 2   Item Type                  110 non-null    object
 3   Outlet Establishment Year  110 non-null    int64
 4   Outlet Identifier          110 non-null    object
 5   Outlet Location Type       110 non-null    object
 6   Outlet Size                110 non-null    object
 7   Outlet Type                110 non-null    object
 8   Item Visibility            110 non-null    float64
 9   Item Weight                110 non-null    float64
 10  Sales                      110 non-null    float64
 11  Rating                     110 non-null    int64
dtypes: float64(3), int64(2), object(7)
memory usage: 10.4+ KB

In [49]:
df.columns

Index(['Item Fat Content', 'Item Identifier', 'Item Type',
       'Outlet Establishment Year', 'Outlet Identifier',
       'Outlet Location Type', 'Outlet Size', 'Outlet Type', 'Item Visibility',
       'Item Weight', 'Sales', 'Rating'],
      dtype='object')

In [50]:
df.describe()

,Outlet Establishment Year,Item Visibility,Item Weight,Sales,Rating
count,110.000000,110.000000,110.000000,110.000000,110.000000
mean,2020.054545,57.263875,3.043636,56.779455,3.990909
std,3.082464,25.699107,1.236489,24.164433,0.840440
min,2015.000000,11.225538,1.100000,11.740000,3.000000
25%,2018.000000,37.459916,2.025000,40.085000,3.000000
50%,2020.000000,54.215109,3.000000,61.410000,4.000000
75%,2023.000000,82.438900,4.100000,75.055000,5.000000
max,2025.000000,99.511662,5.000000,99.970000,5.000000

In [51]:
df.drop_duplicates(inplace=True)

In [52]:
df['Item Type'].unique()

array(['Rice', 'Bread', 'Milk', 'Egg', 'Apple', 'Banana', 'Orange',
       'Mango', 'Grapes', 'Potato', 'Tomato', 'Onion', 'Carrot',
       'Cabbage', 'Spinach', 'Peas', 'Lentils', 'Beans', 'Chicken',
       'Fish', 'Meat', 'Butter', 'Cheese', 'Yogurt', 'Sugar', 'Salt',
       'Tea', 'Coffee', 'Juice', 'Soup', 'Cake', 'Biscuit', 'Chocolate',
       'Ice Cream', 'Noodles', 'Pasta', 'Pizza', 'Burger', 'Sandwich',
       'Salad', 'Pickle', 'Honey', 'Jam', 'Corn', 'Nuts', 'Coconut',
       'Watermelon', 'Papaya', 'Sweets', 'Porridge'], dtype=object)

In [53]:
df['Sales'].sum()

np.float64(6245.739999999999)

In [54]:
df['Sales'].mean()

np.float64(56.779454545454534)

In [55]:
df['Sales'].max()

99.97

In [56]:
df['Sales'].min()

11.74

In [57]:
df.to_excel('Clean_Blinkit_Data.xlsx', index=False)